import Navbar from "@/components/Navbar";
import { ToastContainer } from "react-toastify";
import "./globals.css";
import { Hind_Siliguri, Inter } from "next/font/google";
const inter = Inter({ subsets: ["latin"] });

const siliguri = Hind_Siliguri({
  subsets: ["bengali"],
  weight: ["300", "600"],
  variable: "--font-siliguri",
});

export const metadata = {
  title: "Web App",
  description: "Generated by Inzamamul Karim",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={siliguri.variable}>
        <Navbar />
        {children}
        <ToastContainer
          position="top-right"
          autoClose={5000}
          hideProgressBar={false}
          newestOnTop={false}
          closeOnClick
          rtl={false}
          pauseOnFocusLoss
          draggable
          pauseOnHover
          theme="light"
        />
      </body>
    </html>
  );
}
